services:
  backend:
    build: ./backend
    container_name: mega-backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: mega-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
