
services:
  backend:
    build: ./backend
    container_name: DocChain-backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_BASE_URL: "http://backend:5000/api"
    container_name: DocChain-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
